In [1]:
!pwd

/Users/miguelcamargorojas/Documents/UP/NLP-Ago-dic25/Semana I


In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [9]:
lista = [1, 2, 3, 4, 1.1, True, [], (), "HOla"]
type(lista)

list

In [10]:
arreglo1 = np.asarray(lista)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (9,) + inhomogeneous part.

In [8]:
type(arreglo1)

numpy.ndarray

In [13]:
arreglo2 = np.asarray([1, 1, 1.1, "Hola", True])

In [16]:
arreglo2[0].item()

'1'

In [17]:
arreglo2[0:2]

array(['1', '1'], dtype='<U32')

In [24]:
# i=0; 10; i++ 
list(range(1, 11, 1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [26]:
rango_arreglo = np.arange(10)

In [27]:
type(rango_arreglo)

numpy.ndarray

In [28]:
dir(rango_arreglo)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [29]:
rango_arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
rango_arreglo.shape

(10,)

In [31]:
rango_arreglo.size

10

In [32]:
rango_arreglo.dtype

dtype('int64')

In [33]:
rango_arreglo.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
matriz_python = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [38]:
# Fila, columna
matriz_python[1][1]

5

In [37]:
matriz_python[0, 0]

TypeError: list indices must be integers or slices, not tuple

In [48]:
matriz_python.shape

AttributeError: 'list' object has no attribute 'shape'

In [40]:
matriz_numpy = np.asarray(matriz_python)

In [41]:
matriz_numpy.shape

(3, 3)

In [42]:
matriz_numpy.size

9

In [43]:
matriz_numpy.dtype

dtype('int64')

In [44]:
matriz_numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
matriz_numpy.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
matriz_numpy.reshape((10, 1))

ValueError: cannot reshape array of size 9 into shape (10,1)

In [50]:
matriz_numpy.reshape((9, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [51]:
matriz_numpy.reshape((1, 9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Random

In [56]:
np.random.random()

0.40633052829084193

In [64]:
np.random.randint(0, 101)

100

In [70]:
np.random.randint(0, 101, size=(9, 9))

array([[13, 34, 20, 61, 60, 78, 19, 34, 96],
       [74, 31, 31, 54, 93, 80, 30, 52, 72],
       [90, 14, 10, 98, 43, 14, 19, 28, 48],
       [28, 13,  7, 53, 48, 26, 18, 58, 15],
       [39, 42, 91, 79,  4, 88,  8, 64, 63],
       [54, 12, 30, 32, 24, 64, 67, 68, 94],
       [14, 56,  1, 68,  1, 86, 50, 49,  5],
       [68, 80, 25, 15,  7,  8, 94,  7, 57],
       [38, 37, 49, 26, 49, 79, 46, 97, 11]])

In [71]:
np.random.seed(96)

In [76]:
np.random.randint(0, 101, size=(9, 9))

array([[ 85,  37,  69,   2,  11,  35,  74,  11,  46],
       [ 25,  72,  74,  66,  24,  60,  57,  32,  54],
       [ 30,  70,  35,  50,  52,  73,  25,   2,  44],
       [ 29,  22,  31,  48,   6,  17,  15,  49,  96],
       [ 94,  29,   2,  95,  84,  85,  98,  46,  78],
       [ 33,  52,  83,  35,  88,  80,  64,  32,  49],
       [ 80,  20,  38,  45,  55, 100,  93,  55,  31],
       [ 60,  72,  33,  60,  47,  81,  73,   3,  48],
       [ 99,  95,  27,  23,  62,  23,  15,  22,   3]])